### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by satazor** [moxystudio/react-with-moxy-scripts#2]
`create-react-app` has jest built-in.. I've been thinking about this and I have a lot of doubts:

- jest does not support running tests in real browsers
- jest has strange stuff like relying on globals and auto-mocking
- there's unit, integration and visual tests:
  - jest, mocha and alike only solve unit and integration tests
  - selenium and alike solve the later

We need to come up with a good enough solution for the short/mid term. Having no tests setup at all, encourages not doing any tests for apps..

**Comment by satazor** [comment]
Along the way we will build complex apps and gain more experience at testing them. With more experience we can take wiser decisions.

For the short-term, we should follow cra and offer zero configuration testing based on jest.

**Comment by zebateira** [comment]
I agree. We should offer jest and on the long run think about a more robust solution.

**Comment by andregoncalvesdev** [comment]
To consider: https://github.com/DevExpress/testcafe

**Comment by satazor** [comment]
react-with-moxy now has jest. If e2e testing is a necessity for most projects, we can think about adding them too.
